__title__ = 'tryloguru'
#__package_name__ = 'not-a-package'
__version__ = '0.0.2'
__description__ = "Just an example of using the LoGuru module to remind me about using it."
__email__ = "notNeededForThisExample@null.net"
__author__ = 'Matt McCright'
__github__ = 'https://github.com/mccright/PythonLoggingExamples'
#__pypi__ = 'https://pypi.org/project/ --> not-a-package'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022 - Matt McCright'
